<a href="https://colab.research.google.com/github/DilakshanMadhusanka/KNN_DM/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('Iris.csv')

In [ ]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [ ]:
data['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
data.shape

(150, 6)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
x = data.iloc[:,1:5]
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [ ]:
y = data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
x = scaler.fit_transform(x)
x[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
x_train.shape

(120, 4)

In [ ]:
x_test.shape

(30, 4)

In [ ]:
y_train.shape

(120,)

In [ ]:
y_test.shape

(30,)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)

model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [ ]:
pred = model.predict(x_test)
pred[0:5]

array(['Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor'], dtype=object)

In [ ]:
y_test[0:5]

84     Iris-versicolor
122     Iris-virginica
17         Iris-setosa
30         Iris-setosa
58     Iris-versicolor
Name: Species, dtype: object

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,pred)
accuracy

0.9

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,pred)
cm

array([[12,  0,  0],
       [ 0,  5,  1],
       [ 0,  2, 10]])

In [ ]:
result = pd.DataFrame(data = [y_test.values,pred], index = ['y_test','pred'])
result.transpose()

y_test             pred
0   Iris-versicolor  Iris-versicolor
1    Iris-virginica   Iris-virginica
2       Iris-setosa      Iris-setosa
3       Iris-setosa      Iris-setosa
4   Iris-versicolor  Iris-versicolor
5    Iris-virginica  Iris-versicolor
6    Iris-virginica   Iris-virginica
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9    Iris-virginica   Iris-virginica
10  Iris-versicolor  Iris-versicolor
11   Iris-virginica   Iris-virginica
12  Iris-versicolor   Iris-virginica
13   Iris-virginica   Iris-virginica
14      Iris-setosa      Iris-setosa
15      Iris-setosa      Iris-setosa
16      Iris-setosa      Iris-setosa
17      Iris-setosa      Iris-setosa
18      Iris-setosa      Iris-setosa
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21  Iris-versicolor  Iris-versicolor
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25      Iris-setosa      Iris-setosa
26   Iris-virginica  Iris-versicolor
27      Iris-setosa      Iris-setosa
28      Iris-setosa      Iris-setosa
29   Iris-virginica   Iris-virginica

In [ ]:
correct_sum = []

for i in range(1,20):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    pred = model.predict(x_test)
    correct = np.sum(pred == y_test)
    correct_sum.append(correct)

In [ ]:
correct_sum

[np.int64(27),
 np.int64(27),
 np.int64(27),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28)]

In [ ]:
result = pd.DataFrame(data = correct_sum)
result.index = result.index + 1
result.T

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19
0  27  27  27  28  28  28  28  28  28  28  28  28  28  28  28  28  28  28  28

In [ ]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)
pred = model.predict(x_test)

accuracy = accuracy_score(y_test,pred)
accuracy

0.9333333333333333

In [ ]:
cm = confusion_matrix(y_test,pred)
cm

array([[12,  0,  0],
       [ 0,  6,  0],
       [ 0,  2, 10]])